language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
  - "0.10"
  - "0.12"
  - "4"
script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bce1a1b401d97fe096e2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

# libsass and iconv fails on Node 4.1 (as of 01/10/2015)
matrix:
  allow_failures:
      - node_js: "4"
